### ISSUE TITLE
Vite Setup?

### ISSUE THREAD

**Issue by iampapagray** [DevAccess/vue3-dayjs#1]
I'm using Vue3 with Vite and installed the plugin. 
However i get the error below in my console:

```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource 
at http://[::]:5173/node_modules/.vite/deps/vue3-dayjs-plugin.js?v=686ddce1. (Reason: CORS request did not succeed). 
Status code: (null).
```

Could i be missing something?

**Comment by DevAccess** [comment]
Maybe not installed correctly. Can you run me through the steps you took from installation to getting the error?
Here is a post I found with a similar issue on a different package: https://www.reddit.com/r/vuejs/comments/wut4fd/vuejs_import_lodash_doesnt_work_getting/

**Comment by iampapagray** [comment]
@DevAccess 

i first did `npm i vue3-dayjs-plugin`
Then in my `main.js` i did `import VueDayjs from 'vue3-dayjs-plugin'`

Then 
```
const app = createApp(App)
app.use(VueDajjs)
```

I havent used the library yet in any part of the application beyond installing it

**Comment by iampapagray** [comment]
> Maybe not installed correctly. Can you run me through the steps you took from installation to getting the error? Here is a post I found with a similar issue on a different package: https://www.reddit.com/r/vuejs/comments/wut4fd/vuejs_import_lodash_doesnt_work_getting/

Thanks for the pointer. According to the post above, all i needed to do was run `npm install` again. And everything works fine.

**Comment by DevAccess** [comment]
Yup that's what I was thinking. You installed the package, but it was missing from the app itself which `npm install` fixes. Nice catch.
